dist: xenial
language: python
sudo: false
python:
  - "3.7"
before_install:
  - pip install -U pip
install:
  - travis_wait travis_retry pip install -r requirements.txt
script: pytest -p no:warnings -vv --pep8
branches:
  only:
  - master
  - stable
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
notifications:
  email:
    on_success: never
    on_failure: enver
