dist: xenial
language: python
sudo: false
python:
  - "3.7"
before_install:
  - docker build -t app:latest .
install:
  - docker run
script: ./run-tests
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
notifications:
  email:
    on_success: never
    on_failure: never
