version: 0.2

phases:
  pre_build:
    commands:
      - docker version
      - $(aws ecr get-login --no-include-email)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - docker pull $IMAGE_REPOSITORY:builder || true
  build:
    commands:
      - docker build -t "${IMAGE_REPOSITORY}:${TAG}" .
  post_build:
    commands:
      - echo Running post build `date`
      - echo Docker Images
      - docker image ls -a
      - docker run -i ${IMAGE_REPOSITORY}:${TAG} ls -al
      - docker run -i ${IMAGE_REPOSITORY}:${TAG} ./run-tests
      - docker push "${IMAGE_REPOSITORY}:${TAG}"
