version: 0.2

phases:
  pre_build:
    commands:
      - docker version
      - $(aws ecr get-login --no-include-email)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - docker pull $IMAGE_REPOSITORY:builder || true
  build:
    commands:
      - docker build -t "${IMAGE_REPOSITORY}:${TAG}" .
  post_build:
    commands:
      - docker run -i ${IMAGE_REPOSITORY}:${TAG} /bin/ash -c "chmod +x run-tests; ls -al; ./run-tests"
      - docker push "${IMAGE_REPOSITORY}:${TAG}"
      - printf '[' >> imagedefinitions.json
      - printf '{"name":"talis_app","imageUri":"%s"},' ${IMAGE_REPOSITORY}:${TAG} >> imagedefinitions.json
      - printf '{"name":"talis_wikipedia","imageUri":"%s"},' ${IMAGE_REPOSITORY}:${TAG} >> imagedefinitions.json
      - printf '{"name":"talis_commands","imageUri":"%s"},' ${IMAGE_REPOSITORY}:${TAG} >> imagedefinitions.json
      - printf '{"name":"talis_twitch_nlp","imageUri":"%s"}' ${IMAGE_REPOSITORY}:${TAG} >> imagedefinitions.json
      - printf ']' >> imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
