version: 0.2

phases:
  pre_build:
    commands:
      - docker version
      - $(aws ecr get-login --no-include-email)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - docker pull $IMAGE_REPOSITORY:builder || true
  build:
    commands:
      - docker build --tag "${IMAGE_REPOSITORY}:${TAG}" .
  post_build:
    commands:
      - docker exec -it ${IMAGE_REPOSITORY}:${TAG} ./run-tests
      - docker push "${IMAGE_REPOSITORY}:${TAG}"
