version: 0.2

env:
  variables:
     ENV: test

phases:
  pre_build:
    commands:
      - docker version
      - $(aws ecr get-login --no-include-email)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - docker pull $IMAGE_REPOSITORY:builder || true
  build:
    commands:
      - docker build --cache-from $IMAGE_REPOSITORY:builder --target app --tag "${IMAGE_REPOSITORY}:${TAG}" .
  post_build:
    commands:
      - docker push "${IMAGE_REPOSITORY}:${TAG}"
