version: "3"

services:
    talis_app:
        build:
            context: .
            dockerfile: ./docker/app/Dockerfile
        container_name: talis_app
        command: ./wait-for.sh kafka:9092 -- python twitch_message_producer.py ${CHANNEL}
        ports:
            - "5000:5000"
        depends_on:
            - zookeeper
            - kafka
    zookeeper:
        build:
            context: .
            dockerfile: ./docker/zookeeper/Dockerfile
        container_name: zookeeper
        ports:
            - "2181:2181"
    kafka:
        build:
            context: .
            dockerfile: ./docker/kafka/Dockerfile
        container_name: kafka
        depends_on:
            - zookeeper
        ports:
            - "7203:7203"
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
            ZOOKEEPER_IP: ${HOST_IP}
            #KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka0:29092,OUTSIDE://localhost:9092
            #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
