version: "3"

volumes:
    kafka_data:
    kafka_logs:
    zookeeper_data:
    zookeeper_config:

services:
    # talis_app:
    #     build:
    #         context: .
    #         dockerfile: ./docker/app/Dockerfile
    #     container_name: talis_app
    #     ports:
    #         - "5000:5000"
    #     depends_on:
    #         - zookeeper
    #         - kafka
    # environment:
    # WAIT_HOSTS: kafka:9092
    zookeeper:
        build:
            context: .
            dockerfile: ./docker/zookeeper/Dockerfile
        container_name: zookeeper
        volumes:
            - zookeeper_config:/opt/zookeeper/conf
            - zookeeper_data:/tmp/zookeeper
        ports:
            - "2181:2181"
    kafka:
        build:
            context: .
            dockerfile: ./docker/kafka/Dockerfile
        container_name: kafka
        volumes:
            - kafka_data:/data
            - kafka_logs:/logs
        ports:
            - "7203:7203"
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
            ZOOKEEPER_IP: ${ZOOKEEPER_IP}
            ZOOKEEPER_PORT: ${ZOOKEEPER_PORT}
            #KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka0:29092,OUTSIDE://localhost:9092
            #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
